### ISSUE TITLE
Menu bar not visible when using Awesome UI plugin.

### ISSUE THREAD

**Issue by aforank** [lee88688/logseq-drawio-plugin#1]
First of all. Thank you for taking time and creating this plugin. I am sure a lot of people would be looking for the same. 

However, I tried using it today, and it seems like if Tabs plugin is installed, Menu bar along with buttons to save and exit from draw.io are not visible. I couldn't find any other way to close the overlay. Please check the screennshot. 

![image](https://github.com/lee88688/logseq-drawio-plugin/assets/19813442/95c933da-6b48-4b7d-bef8-847ad261ba7b)

**Comment by lee88688** [comment]
original tabs plugin does not have this problem. you may install 'Awesome UI' plugin. this is easy to resolve. please wait for new version.

**Comment by aforank** [comment]
@lee88688 Yes, I am using Awesome UI plugin. I tried again on the newer version 1.0.2, it has improved slightly but still I can't see the Menu bar and other buttons. 

![image](https://github.com/lee88688/logseq-drawio-plugin/assets/19813442/8d21b99c-7882-4c42-a7a0-8c66d4d1b3da)

**Comment by lee88688** [comment]
could you tell what plugins and current theme that you use? I can't replay it.

**Comment by aforank** [comment]
Awesome UI plugin is causing the problem. I disabled it temporarily and it worked just fine. Could you please check now?

**Comment by lee88688** [comment]
Awesome UI changes whole logseq html(body) heigh which is more than window.innerHeight. plugin container use `absolute` position which causes inner iframe's height is more than window view port heigth and it finally causes menus disappear.
![image](https://github.com/lee88688/logseq-drawio-plugin/assets/5847884/85d6e3e8-7d87-4e72-bc4f-c367cdc9e743)

it is not commonly modifying iframe's container style. so I may not fix this issue soon. wait for Awesome UI author's udpates and it may fix this issue.

**Comment by aforank** [comment]
Closing it as it appears fine now.
