### ISSUE TITLE
Doesn't render images when exported

### ISSUE THREAD

**Issue by MagnusHallas** [lee88688/logseq-drawio-plugin#10]
The rendered images don't not show when the block is exported from logseq (HTML export and through the export pdf plugin). Maybe it is possible, but I haven't been able to do it. Otherwise, a really cool plugin, thank you!

**Comment by lee88688** [comment]
what plugin do you use?

**Comment by MagnusHallas** [comment]
Do you mean for the export? For the pdf export, I use this one https://github.com/sawhney17/logseq-pdf-export

**Comment by lee88688** [comment]
You may need to use "Print With Retained Formatting" to export to PDF. The first three templates use original markdown to export to PDF. Plugin-rendered content is not inlined in block content and is rendered by the plugin at runtime. I don’t know whether the PDF plugin supports asking the plugin to get content.

**Comment by MagnusHallas** [comment]
That sort of works, but in my case I only get one of the two pages printed (two pages in the pdf, but the second one is blank). Maybe this is not an issue with the draw.io plugin but the export options in Logseq?

**Comment by lee88688** [comment]
yes, logseq need to give more effort to improve.
