### ISSUE TITLE
如何更新到drawio的最新版

### ISSUE THREAD

**Issue by AoThen** [lee88688/logseq-drawio-plugin#11]
如何更新到drawio的最新版，技术不到家，fork后没找到对应更新的地方😂😂

**Comment by lee88688** [comment]
在logseq里面安装就好了

**Comment by AoThen** [comment]
![image](https://github.com/lee88688/logseq-drawio-plugin/assets/32790381/137c808b-c221-408c-91fb-423be0f10f64)
是这个drawio版本😂😂

**Comment by lee88688** [comment]
不好意思我看错了，更新版本需要git中更新drawio的submodule到最新就好了

**Comment by AoThen** [comment]
好，谢谢🤓
