### ISSUE TITLE
External image does not render

### ISSUE THREAD

**Issue by shinglyu** [lee88688/logseq-drawio-plugin#12]
I tried to drag and drop an external image (e.g. https://en.wikipedia.org/wiki/File:ServiceNow_logo.svg) into my diagram. But when I save it it does not render:

![Screenshot 2024-01-08 at 14 19 34](https://github.com/lee88688/logseq-drawio-plugin/assets/3250983/28d02bfc-567f-4568-868a-7f402cdc4a4b)

If I export it to png in draw.io > File > Export as > PNG, it is also not rendering. 

Tried dragging in PNG and SVG, both don't work.

**Comment by lee88688** [comment]
it seems [`embedImages`](https://www.drawio.com/doc/faq/embed-mode) should be set to true. I will test it later.

**Comment by lee88688** [comment]
after my test, the embeded drawio will embed images by default. if you download the svg you give and drag and drop into embeded drawio, this will show images. but if you directly copy from browser, this will fail.
so I think this is drawio's issue, you can use drawio's electron or web app to test and post an issue to him.
