### ISSUE TITLE
Where are the .drawio files stored and how can I get them?

### ISSUE THREAD

**Issue by petruut** [lee88688/logseq-drawio-plugin#13]
I can only see .svgs in the graph folder, but I can't find the editable .drawio files.

I want to be able to edit the diagrams outside of my graph and share the editable version with other people. Where are the files stored?

Many thanks!!

**Comment by lee88688** [comment]
you can find a download svg button when hover the draw. the svg file can be directly edted by drawio which you can share with other people.
