### ISSUE TITLE
Ability to name the svg/ block, for easier reference and retrieval

### ISSUE THREAD

**Issue by petruut** [lee88688/logseq-drawio-plugin#14]
I built a diagram and i want to reference again, and ideally duplicate + add changes/ variations to. I'd like to have some functionality built in to help me find the diagram, and then duplicate it in a way where the original and the changed coexist.

I love this plugin by the way. It actually makes Logseq a lot better for me.

**Comment by lee88688** [comment]
if you want to cite the existing draw, just copy the macro (when edit block, not edit the draw, the macro will be like `{{renderer :drawio, 1702957105923.svg}}`) and paste it to other place. or just embed this block to other block.
if you want to find the draw, you should add some tags or properties to the block. later you can use these to find it.
if you want to duplicate it, you can just edit draw, then copy it and paste it to new draw.
