### ISSUE TITLE
(PDF) export location

### ISSUE THREAD

**Issue by TobiasFrahm** [lee88688/logseq-drawio-plugin#20]
Hello, 
sorry for this stupid request, but can anyone tell me where I do find the pdf exports? I cannot find it in my logseq-graph folder nor in the ~/.logseq neither in my downloads.

**Comment by lee88688** [comment]
did you mean my plugin's pdf export? currently this plugin does not have this feature

**Comment by TobiasFrahm** [comment]
If I edit a drawing from logseq (click on the edit button which shows up on mouseover) draw.io will open. Then I can go to File → Export as → PDF

This is visible at least, but does not seem to work. Not sure how/if this is related to your plugin tbh...

**Comment by lee88688** [comment]
I tested it. it may be an issue of my plugin. but when I export other types, it will sussess. it will take some time to explore why.

**Comment by lee88688** [comment]
I think this is a bug from drawio's embeded mode. when I update drawio to latest version, pdf can't be downloaded. other formats can be downloaded.
