### ISSUE TITLE
Toolbar buttons may be hard to see

### ISSUE THREAD

**Issue by 0w0miki** [lee88688/logseq-drawio-plugin#3]
I am using a modified version of Dracular theme. The toolbar button is a bit hard to see with white content.
![图片](https://github.com/lee88688/logseq-drawio-plugin/assets/18544315/2551cc77-7a27-40d2-aaec-77e9cc14e732)

I think logseq native image overlay could be a solution.
![图片](https://github.com/lee88688/logseq-drawio-plugin/assets/18544315/a03abb06-a7c5-4ecd-9096-589f37053617)

**Comment by lee88688** [comment]
emm, good idea
