### ISSUE TITLE
在MacOS中不会随LogSeq的主题变化，永远都是暗色主题

### ISSUE THREAD

**Issue by entps** [lee88688/logseq-drawio-plugin#4]
在MacOS中不会随LogSeq的主题变化，永远都是暗色主题，希望能够随主题变化而变化，再就是打开编辑器时有一片空白区域
![iShot_2023-08-04_09 37 25](https://github.com/lee88688/logseq-drawio-plugin/assets/125341841/a2f7ca21-89fa-4d4b-b38c-5a0be30813f1)

**Comment by lee88688** [comment]
我没有mac，在Windows上最新版本主题是跟随logseq的，你可以更新版本试试。
