### ISSUE TITLE
There is a blank area above. 

### ISSUE THREAD

**Issue by entps** [lee88688/logseq-drawio-plugin#5]
There is a blank area above. Recommended to change it to a simple style and an embedded drawio
![iShot_2023-08-06_17 29 29](https://github.com/lee88688/logseq-drawio-plugin/assets/125341841/a04edf7d-9597-46ae-8be8-ec8fc8ac55c0)

simple style
![iShot_2023-08-06_17 25 56](https://github.com/lee88688/logseq-drawio-plugin/assets/125341841/4844c35e-5c12-438c-ad02-49e1c1832b4a)

**Comment by lee88688** [comment]
blank area is used for dragging app, may be it should be smaller. simple style is one of themes in draw.io. maybe theme setting needs to provide for users.
