### ISSUE TITLE
建议再增加 明亮、暗黑、自动 的UI风格显示参数设置

### ISSUE THREAD

**Issue by entps** [lee88688/logseq-drawio-plugin#7]
建议再增加 明亮、暗黑、自动 的UI风格显示参数设置

**Comment by lee88688** [comment]
that sounds good

**Comment by redgallows** [comment]
First of all, thanks for making this useful plugin.
I would second on this, I always use "dark" theme for Logseq, however, the drawio dark theme is really hard to use. It will be good if the drawio plugin theme setting could be independently separated from Logseq.

Thank you.

**Comment by redgallows** [comment]
OMG, I can't thank you enough for the quick response and implementation.
